-- INNER JOIN
SELECT
	*
FROM Candidato T01
	JOIN Empresa T02 ON T02.Id = T01.EmpresaId



--LEFT JOIN
SELECT 
	* 
FROM Candidato T01 
	LEFT JOIN Empresa T02 ON T02.Id = T01.EmpresaId 
--WHERE T02.Id IS NULL


--RIGHT JOIN
SELECT 
	* 
FROM Candidato T01 
	RIGHT JOIN Empresa T02 ON T02.Id = T01.EmpresaId 
--WHERE T01.Id IS NULL